FROM python:3.11-slim

WORKDIR /app

COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

COPY src/ ./src/
COPY data/processed/churn_predictions.csv ./data/processed/churn_predictions.csv
COPY data/processed/rfm.csv ./data/processed/rfm.csv

EXPOSE 8000

CMD ["uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
